[package]
name = "quantum-soft-keyboard"
version = "0.1.0"
authors = ["Wayne Warren <wayne.warren.s@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev-rs = "~0.3"
nix = "~0.13"
async-std = { version = "~1.5", features = ["unstable"] }

# cli
clap = "~2.33"
fern = "~0.5" # log implementation

# logging
log = "~0.4"
