[package]
name = "quantum-soft-keyboard"
version = "0.1.0"
authors = ["Wayne Warren <wayne.warren.s@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev-rs = { git = "https://github.com/ndesh26/evdev-rs", ref = "5a7a8484cf07ecad41710ca4399582cf8f565e90" }
nix = "~0.17"
async-std = { version = "~1.5", features = ["unstable"] }
chrono = "~0.4"

# cli
clap = "~2.33"
fern = "~0.5" # log implementation

# logging
log = "~0.4"
